sudo: required
services:
  - docker

before_install:
  - docker build -t zpalin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zpalin/react-test npm test

after_success:
  - docker build -t zpalin/multi-client ./client
  - docker build -t zpalin/multi-server ./server
  - docker build -t zpalin/multi-nginx ./nginx
  - docker build -t zpalin/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push Images to Docker Hub
  - docker push zpalin/multi-client
  - docker push zpalin/multi-server
  - docker push zpalin/multi-nginx
  - docker push zpalin/multi-worker
