sudo: required
services:
  - docker

before_install:
  - docker build -t zpalin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zpalin/react-test npm test

after_success:
  - docker build -t zpalin/multi-client ./client
  - docker build -t zpalin/multi-server ./server
  - docker build -t zpalin/multi-nginx ./nginx
  - docker build -t zpalin/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push Images to Docker Hub
  - docker push zpalin/multi-client
  - docker push zpalin/multi-server
  - docker push zpalin/multi-nginx
  - docker push zpalin/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-275190232342
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
